version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: mihi_postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mihi_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    image: mustmihi/mihi-api:latest
    container_name: mihi_node_api
    restart: always
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: mihi_db
      PORT: 3000
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:
